config/routes.rb
require "sidekiq/web"
require "letter_opener_web"

Rails.application.routes.draw do
  get "reports", to: "reports#index"
  get "reports/savings"
  get "reports/savings_per_year"
  get "reports/lent"
  get "reports/unfinished_ended"
  resources :articles
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new
  mount(LetterOpenerWeb::Engine, at: "/letter_opener", constraints: AdminConstraint.new) if Rails.env.staging? || Rails.env.development?
  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :show]
      resources :works, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
        end
      end
    end
  end

  resources :reservations, except: [:new]

  resources :draft_invoices do
    collection do
      post :reset # , to: 'draft_invoices#reset'
    end
    resources :invoice_items do # , only: [:new, ,:destroy, :create] do
      get :edit_discount
    end
    get :mutation_form
    post :create_invoice
    patch :finalize_invoice
    patch :reviewed
    patch :refresh
  end

  resources :invoices do
    get "old_data", to: "invoices#old_data"
    get :specification, to: "invoices#specification"
    member do
      post :register_payment
      patch :on_hold
    end
  end

  resources :customers do
    get "raw", to: "customers#raw"
    resources :time_spans
    resource :collect_mandate
    resources :invoices
  end

  resources :collections do
    resources :works do
      resources :reservations
      resource :return, only: [:new, :create]
    end
  end

  resources :works, only: :show

  post "/auth/:provider/callback", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/new", to: "sessions#new"
  get "/application_status", to: "application#status"
  delete "/auth", to: "sessions#destroy", as: :auth

  root "application#home"
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                       :integer          not null, primary key
#  allow_discount           :boolean          default(TRUE)
#  external_article_code    :string
#  external_article_subcode :string
#  name                     :string
#  vat_rate                 :decimal(, )
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#
class Article < ApplicationRecord
  validates_presence_of :name, :external_article_code
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to article_url(@article), notice: "Artikel aangemaakt."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    if @article.update(article_params)
      redirect_to article_url(@article), notice: "Artikel bijgewerkt."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    redirect_to articles_url, notice: "Artikel is verwijderd."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:external_article_code, :external_article_subcode, :name, :vat_rate)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors.to_a.to_sentence if f.object.errors.present? %>

  <div class="form-inputs">
    <%= f.input :external_article_code, required: true %>
    <%= f.input :external_article_subcode, required: false %>
    <%= f.input :name %>
    <%= f.input :vat_rate, as: :float %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1>Artikelen</h1>


<ul>
  <% @articles.each do |article| %>
  <li><%= link_to article.name, article%></li>
  <% end %>
</ul>

<p>Let op: Artikelen zijn middels een externe artikelcode (en eventueel een artikelsubcode) geregistreerd in het boekhoudpakket. De Btw tarieven zijn er enkel voor een eerste berekening, de waarheid staat in het boekhoudpakket.</p>

<%= link_to "Voeg artikel toe", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.name%></h1>

<dl id="<%= dom_id @article %>">
  <dt>Externe artikelcode:</dt>
  <dd><%= [@article.external_article_code, @article.external_article_subcode].join("/") %></dd>
  <dt>Btw-tarief (informatief)</dt>
  <dd><%= @article.vat_rate %>%</dd>
</dl>


<div>
  <%= link_to "Bewerk", edit_article_path(@article) %> |
  <%= button_to "Verwijder dit artikel", @article, method: :delete %>
</div>