config/routes.rb
require "sidekiq/web"
require "letter_opener_web"

Rails.application.routes.draw do
  get "reports", to: "reports#index"
  get "reports/savings"
  get "reports/savings_per_year"
  get "reports/lent"
  get "reports/unfinished_ended"
  resources :articles
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new
  mount(LetterOpenerWeb::Engine, at: "/letter_opener", constraints: AdminConstraint.new) if Rails.env.staging? || Rails.env.development?
  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :show]
      resources :works, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
        end
      end
    end
  end

  resources :reservations, except: [:new]

  resources :draft_invoices do
    collection do
      post :reset # , to: 'draft_invoices#reset'
    end
    resources :invoice_items do # , only: [:new, ,:destroy, :create] do
      get :edit_discount
    end
    get :mutation_form
    post :create_invoice
    patch :finalize_invoice
    patch :reviewed
    patch :refresh
  end

  resources :invoices do
    get "old_data", to: "invoices#old_data"
    get :specification, to: "invoices#specification"
    member do
      post :register_payment
      patch :on_hold
    end
  end

  resources :customers do
    get "raw", to: "customers#raw"
    resources :time_spans
    resource :collect_mandate
    resources :invoices
  end

  resources :collections do
    resources :works do
      resources :reservations
      resource :return, only: [:new, :create]
    end
  end

  resources :works, only: :show

  post "/auth/:provider/callback", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/new", to: "sessions#new"
  get "/application_status", to: "application#status"
  delete "/auth", to: "sessions#destroy", as: :auth

  root "application#home"
end

app/controllers/time_spans_controller.rb
class TimeSpansController < ApplicationController
  DISPLAY_SCOPES = [:reservations, :rental_outgoing, :history]
  before_action :set_customer
  before_action :set_time_span, only: [:show]

  def index
    @display_scope = DISPLAY_SCOPES.include?(params[:scope]&.to_sym) ? params[:scope].to_sym : DISPLAY_SCOPES.first

    if @display_scope == :reservations
      @current_reservations = CollectionManagement::TimeSpan.where(current_user: current_user, contact_url: @customer.uri, status: [:reservation], current: true, limit: 100).select(&:subject).select(&:subject)
    elsif @display_scope == :rental_outgoing
      @current_rentals = CollectionManagement::TimeSpan.where(current_user: current_user, contact_url: @customer.uri, status: [:active], classification: :rental_outgoing, limit: 100).select(&:subject)
    elsif @display_scope == :history
      @purchases = CollectionManagement::TimeSpan.where(current_user: current_user, contact_url: @customer.uri, status: [:active, :finished], classification: :purchase, limit: 100).select(&:subject)
      @finalized_rentals = CollectionManagement::TimeSpan.where(current_user: current_user, contact_url: @customer.uri, status: [:finished], classification: :rental_outgoing, limit: 100).select(&:subject)
    end
  end

  def show
  end

  private

  def set_time_span
    @time_span = CollectionManagement::TimeSpan.find(params[:id])
    raise ActiveRecord::RecordNotFound.new("Timespan not found for this user") if @time_span.contact_url != @customer.uri
  end

  def set_customer
    @customer = Customer.find_by!(uuid: params[:customer_id])
  end
end

app/views/collection_management/time_spans/_time_span.html.erb
<article class="time_span">
  <p class="meta">
    <%= link_to customer_time_span_path(@customer, time_span) do %>
      <% if time_span.reservation? %>
        <%= I18n.t time_span.status, scope: :status %>   <%= I18n.t(time_span.classification, scope: "activerecord.values.time_span.classification").downcase%> <%= I18n.l time_span.starts_at, format: :short if time_span.starts_at %> - <%= I18n.l time_span.ends_at, format: :short if time_span.ends_at %></p>
      <% elsif time_span.classification == "rental_outgoing"%>
        <%= I18n.t time_span.status, scope: :status %> <%= I18n.l time_span.starts_at, format: :short if time_span.starts_at %> - <%= I18n.l time_span.ends_at, format: :short if time_span.ends_at %></p>
      <% else %>
        <%= I18n.t time_span.classification, scope: "activerecord.values.time_span.classification"%>
        <%= I18n.t time_span.status, scope: :status %> <%= I18n.l time_span.starts_at, format: :short if time_span.starts_at %> - <%= I18n.l time_span.ends_at, format: :short if time_span.ends_at %></p>
      <% end %>
    <% end %>
  <%= render time_span.subject %>
</article>