config/routes.rb
require "sidekiq/web"
require "letter_opener_web"

Rails.application.routes.draw do
  get "reports", to: "reports#index"
  get "reports/savings"
  get "reports/savings_per_year"
  get "reports/lent"
  get "reports/unfinished_ended"
  resources :articles
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new
  mount(LetterOpenerWeb::Engine, at: "/letter_opener", constraints: AdminConstraint.new) if Rails.env.staging? || Rails.env.development?
  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :show]
      resources :works, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
        end
      end
    end
  end

  resources :reservations, except: [:new]

  resources :draft_invoices do
    collection do
      post :reset # , to: 'draft_invoices#reset'
    end
    resources :invoice_items do # , only: [:new, ,:destroy, :create] do
      get :edit_discount
    end
    get :mutation_form
    post :create_invoice
    patch :finalize_invoice
    patch :reviewed
    patch :refresh
  end

  resources :invoices do
    get "old_data", to: "invoices#old_data"
    get :specification, to: "invoices#specification"
    member do
      post :register_payment
      patch :on_hold
    end
  end

  resources :customers do
    get "raw", to: "customers#raw"
    resources :time_spans
    resource :collect_mandate
    resources :invoices
  end

  resources :collections do
    resources :works do
      resources :reservations
      resource :return, only: [:new, :create]
    end
  end

  resources :works, only: :show

  post "/auth/:provider/callback", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/new", to: "sessions#new"
  get "/application_status", to: "application#status"
  delete "/auth", to: "sessions#destroy", as: :auth

  root "application#home"
end

app/controllers/draft_invoices_controller.rb
class DraftInvoicesController < ApplicationController
  include ClearRedirect
  before_action :configure_twinfield, only: %i[create_invoice show finalize_invoice]
  before_action :set_draft_invoice, only: %i[show edit update destroy create_invoice finalize_invoice mutation_form reviewed refresh]
  before_action :sync_remote_invoice, only: :show

  # GET /draft_invoices/1 or /draft_invoices/1.json
  def show
    if @draft_invoice.finalized?
      redirect_to invoice_path(@draft_invoice)
    else
      authorize! :show, @draft_invoice
    end
  end

  # GET /draft_invoices/1/edit
  def edit
    authorize! :edit, @draft_invoice
  end

  # POST /draft_invoices or /draft_invoices.json
  def create
    authorize! :create, Invoice

    @draft_invoice = Invoice.new(draft_invoice_params)

    respond_to do |format|
      if @draft_invoice.save
        format.html { redirect_to draft_invoice_path(@draft_invoice), notice: "De voorlopige factuur is aangemaakt." }
        format.json { render :show, status: :created, location: @draft_invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @draft_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /draft_invoices/1 or /draft_invoices/1.json
  def update
    authorize! :update, @draft_invoice

    if @draft_invoice.update(draft_invoice_params)
      @draft_invoice.update_rent_quantities_based_on_recurrence_interval
      redirect_to draft_invoice_path(@draft_invoice), notice: "De voorlopige factuur is bijgewerkt."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @draft_invoice

    if @draft_invoice.destroy
      redirect_to new_draft_invoice_url, notice: "De concept factuur is verwijderd"
    else
      redirect_to draft_invoice_url(@draft_invoice), notice: "De factuur kon niet worden verwijderd"
    end
  end

  def refresh
    authorize! :update, @draft_invoice

    @draft_invoice.invoice_items.works.destroy_all
    @draft_invoice.update_rent_quantities_based_on_recurrence_interval
    @draft_invoice.save
    redirect_to draft_invoice_path(@draft_invoice), notice: "De voorlopige factuur is bijgewerkt."
  end

  def create_invoice
    if @draft_invoice.save_external_invoice!
      redirect_to draft_invoice_url(@draft_invoice), notice: "De factuur in het boekhoudprogramma is bijgewerkt"
    else
      redirect_to draft_invoice_url(@draft_invoice), notice: "Er is een fout opgetreden bij het maken van de factuur in het boekhoudprogramma"
    end
  rescue Twinfield::Create::Error => e
    redirect_to draft_invoice_url(@draft_invoice), notice: "Er is een fout opgetreden bij het maken van de factuur in het boekhoudprogramma: #{e.message}"
  end

  # PATCH
  def finalize_invoice
    authorize! :finalize, Invoice

    if @draft_invoice.finalize!
      finalized_invoice = @draft_invoice

      reset_draft_invoice

      UpdateTransactionCopiesWorker.perform_async

      redirect_to invoice_url(finalized_invoice), notice: "De factuur is defintief in het boekhoudprogramma opgeslagen."
    else
      message = @draft_invoice.errors.full_messages.to_sentence
      if message.blank?
        redirect_to draft_invoice_url(@draft_invoice), notice: "Er is een fout opgetreden bij het defintief aanmaken van de factuur in het boekhoudprogramma"
      else
        redirect_to draft_invoice_url(@draft_invoice), notice: message
      end
    end
  rescue Twinfield::Create::Finalized => e
    redirect_to invoice_url(finalized_invoice), notice: "De factuur kon niet definitief worden gemaakt (#{e.message})"
  end

  def new
    invoiceable_item_collection = if params[:invoiceable_item_collection_type] == "CollectionManagement::WorkSet" && params[:invoiceable_item_collection_external_id]
      CollectionManagement::WorkSet.find(params[:invoiceable_item_collection_external_id])
    end

    reset(with: {
      invoiceable_item_collection: invoiceable_item_collection
    })
  rescue SynchroniseInvoiceWorkSetWorker::UnexpectedMultipleCustomersError, SynchroniseInvoiceWorkSetWorker::NoCustomerSetError, SynchroniseInvoiceWorkSetWorker::CustomerMisMatchError => e
    reset(alert: "Er zit een fout in de werkgroepering en de gekoppelde tijdsspanne, kijk de groepering na in CollectionManagement: #{e.message}")
  end

  def reset(with: {}, notice: nil, alert: nil)
    authorize! :new, Invoice

    @draft_invoice = Invoice.create(with.merge(created_by_user: current_user))
    session[:draft_invoice_id] = @draft_invoice.id
    clean_redirect = clear_redirect_destination(params[:return_to], default: nil)
    if clean_redirect
      redirect_to clean_redirect, notice: notice || "Klantsessie is gereset"
    else
      redirect_to draft_invoice_path(@draft_invoice), notice: notice || "Een leeg voorstel is klaargezet", alert: alert
    end
  end

  def mutation_form
  end

  def reviewed
    authorize! :review, @draft_invoice

    if @draft_invoice.update(requires_review_at: nil)
      redirect_to draft_invoice_path(@draft_invoice), notice: "De factuur is gemarkeerd als gecontroleerd"
    else
      redirect_to draft_invoice_path(@draft_invoice), alert: "De factuur kon niet worden gemarkeerd als gecontroleerd"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_draft_invoice
    @draft_invoice = Invoice.includes(:invoice_items).find_by_id_param!(id_param)
    if @draft_invoice.finalized?
      # create a new invoice when finalized on draft invoices
      @draft_invoice = Invoice.create(created_by_user: current_user)
      session[:draft_invoice_id] = @draft_invoice.id
    end
    @draft_invoice.created_by_user = current_user

    set_twinfield_invoice
  end
  alias_method :reset_draft_invoice, :set_draft_invoice

  def set_twinfield_invoice
    if @draft_invoice.twinfield_invoicenumber
      @twinfield_invoice = Twinfield::SalesInvoice.find(@draft_invoice.twinfield_invoicenumber, invoicetype: "FACTUUR")
      @twinfield_invoice.uitleen_invoice = @draft_invoice
    end
  rescue Savon::SOAPFault
    Finance.configure_twinfield
  end

  # Only allow a list of trusted parameters through.
  def draft_invoice_params
    params.require(:invoice).permit(:twinfield_customer_code, :footertext, :po_number, :customer_id, :rental_type, :use_customer_savings_for_purchase, :mutation_form, :recurrence_interval_in_months, :requires_review, :reference, :invoice_item_start_date_reset, new_intent_attributes: [:work_id, :intent], remove_intent_attributes: [:work_id, :intent])
  end

  def sync_remote_invoice
    if @draft_invoice.customer && @draft_invoice.invoice_items.count > 0 && !@draft_invoice.finalized_at
      @draft_invoice.save_external_invoice!
      set_twinfield_invoice
    end
  rescue Twinfield::Create::Error => e
    @invoice_error = "Er is iets mis gegaan bij het synchoniseren van de factuur met het boekhoudpakket: #{e.message}"
    Rails.logger.warn "Invoice not synced as it didn't comply (#{e.message})"
  end

  def id_param
    params[:invoice_id] || params[:draft_invoice_id] || params[:id]
  end
end

app/views/draft_invoices/_form.html.erb
<%= simple_form_for(@draft_invoice, url: draft_invoice_url(@draft_invoice)) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors.to_a.to_sentence if f.object.errors.present? %>


  <fieldset class="form-inputs">
    <%= f.input :rental_type, collection: Invoice::RENTAL_TYPES.collect{|a| [I18n.t(a, scope: "activerecord.values.invoice.rental_type"), a]}.to_h, include_blank: false %>
    <%= f.input :use_customer_savings_for_purchase %>
    <%= f.input :recurrence_interval_in_months %>
    <%= f.input :requires_review, as: :boolean%>
  </fieldset>
  <fieldset>
    <p>De startdatum wordt hiermee overschreven.</p>
    <%= f.input :invoice_item_start_date_reset, as: :date, html5: true %>
  </fieldset>
  <fieldset class="form-inputs">

    <%= f.input :reference %>
    <%= f.input :po_number %>
    <%= f.input :footertext %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/draft_invoices/_mutation_form.html.erb
<%= simple_form_for(@draft_invoice, url: draft_invoice_url(@draft_invoice)) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors.to_a.to_sentence if f.object.errors.present? %>


  <div class="form-inputs">
    <%= f.input :mutation_form %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/draft_invoices/edit.html.erb
<h1>Bewerk concept factuur</h1>

<%= render 'form', draft_invoice: @draft_invoice %>

<%= link_to 'Terug', draft_invoice_path(@draft_invoice) %>

app/views/draft_invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Draft Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Footertext</th>
      <th>Created by user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @draft_invoices.each do |draft_invoice| %>
      <tr>
        <td><%= draft_invoice.customer&.name %></td>
        <td><%= draft_invoice.footertext %></td>
        <td><%= draft_invoice.created_by_user_id %></td>
        <td><%= link_to 'Show', draft_invoice_url(draft_invoice.id) %></td>
        <td><%= link_to 'Edit', edit_draft_invoice_path(draft_invoice.id) %></td>
        <td><%= link_to 'Destroy', draft_invoice_url(draft_invoice.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Draft Invoice', new_draft_invoice_path %>

app/views/draft_invoices/mutation_form.html.erb
<div class="not-for-print">
<h1>Baliemutatie voor <%= @draft_invoice.customer&.name %></h1>
<p>Print deze pagina, laat de klant deze pagina ondertekenen en upload deze vervolgens hier (of ); de printweergave van deze pagina verbergt deze toelichting formuliervelden.</p>
<% if @draft_invoice.mutation_form.present? %><%= link_to "Download mutatieformulier", url_for(@draft_invoice.mutation_form)%><% end %>
<%= render partial: "mutation_form"%>
<hr />

  <nav role="actions">
    <ul>
      <li><%= link_to "Afdrukken", "javascript:window.print();", class: [:secondary, :button]%></li>
    </ul>

  </nav>

</div>

<div class="print-preview">
<section class="invoice">
  <%= render partial: "organisation_address"%>


  <% if @draft_invoice.customer %>
    <address><%=simple_format @draft_invoice.customer.invoice_address%></address>
  <% end %>

  <p><%=I18n.l(@draft_invoice.invoice_date, format: :long) if @draft_invoice.invoice_date%></p>

  <h2>Te huren werken</h2>
  <ul class="works cards">
    <%= render @draft_invoice.invoice_items.rent %>
  </ul>

  <hr />
  <p>Handtekening voor akkoord:
<br/>
<br/>
<br/>
<br/>
<%=@draft_invoice.customer.name%>

</p>

</section>

app/views/draft_invoices/show.html.erb
<nav role="actions">
  <ul>
    <% if can?(:destroy, @draft_invoice) %>
      <li><%= button_to "Verwijder", draft_invoice_path(@draft_invoice), method: :delete, data: {confirm: "Weet je zeker dat je deze concept factuur wilt verwijderen"}, class: [:button, :alert] %></li>


    <% end %>
        <% if @draft_invoice.finalized?%>
    <% elsif @draft_invoice.requires_review? %>
      <li><%= link_to "Bewerk", edit_draft_invoice_path(@draft_invoice)%></li>
      <li><%= button_to "Keur goed", draft_invoice_reviewed_path(@draft_invoice), method: :patch%></li>
    <% elsif @draft_invoice.invoice_number %>
      <li><%= link_to "Bewerk", edit_draft_invoice_path(@draft_invoice)%></li>
      <li><%= link_to "Mutatieformulier", draft_invoice_mutation_form_path(@draft_invoice)%></li>
      <li><%= button_to "Maak definitief", draft_invoice_finalize_invoice_url(@draft_invoice), method: :patch %></li>
    <% elsif !@draft_invoice.invoice_number && @draft_invoice.customer && @draft_invoice.invoice_items.count > 0 %>
      <li><%= link_to "Bewerk", edit_draft_invoice_path(@draft_invoice)%></li>
      <li><%= button_to "Maak factuurberekening", draft_invoice_create_invoice_url(@draft_invoice), method: :patch %></li>
    <% else %>
      <li><%= link_to "Bewerk", edit_draft_invoice_path(@draft_invoice)%></li>
    <% end %>

  </ul>
</nav>
<h1>Opdracht</h1>
<div class="u-columns">
<div class="intent">
<h2>Klant</h2>
<% if @draft_invoice.customer %>
  <%= link_to @draft_invoice.customer&.name, @draft_invoice.customer %>
<% else %>
  <p><%= link_to "Zoek of maak een klant", customers_path%></p>
<% end %>
<h2>Aan te kopen werken</h2>

<% if @draft_invoice.purchase_invoice_items.works.empty? %>
  <p>Geen, <%= link_to "zoek een werk", collections_path%></p>
<% else %>
  <ul class="works cards" data-controller="draft-invoice-invoice_items">
    <% @draft_invoice.purchase_invoice_items.works.each do |intent| %>
        <%= render intent %>
    <% end %>
  </ul>
  <p><%= link_to "Zoek nog een werk", collections_path%> om te verkopen</p>

<% end %>

<h2>Te huren werken</h2>
<% if @draft_invoice.rent_invoice_items.works.empty? %>
  <p>Geen, <%= link_to "zoek een werk", collections_path%></p>
<% else %>
  <ul class="works cards">
    <% @draft_invoice.rent_invoice_items.works.each do |intent| %>
      <%= render intent %>
    <% end %>
  </ul>
  <p><%= link_to "Zoek nog een werk", collections_path%> om te verhuren</p>

<% end %>
<h2>Verder te factureren</h2>
<% if @draft_invoice.non_work_invoice_items.empty? %>
<p>Geen, voeg <%= link_to "een cadeaubon", new_draft_invoice_invoice_item_path(@draft_invoice, params: {invoiceable_type: "GiftCard"})%> of <%= link_to "een andere regel", new_draft_invoice_invoice_item_path(@draft_invoice)%> toe.</p>
<% else %>
<ul>
  <% @draft_invoice.non_work_invoice_items.each do |oii| %>
    <li><%= render oii%></li>
  <% end %>
</ul>
<p>Voeg <%= link_to "een cadeaubon", new_draft_invoice_invoice_item_path(@draft_invoice, params: {invoiceable_type: "GiftCard"})%> of <%= link_to "een andere regel", new_draft_invoice_invoice_item_path(@draft_invoice)%> toe.</p>
<% end%>
<% unless @draft_invoice.finalized? %>
<h2>Verder</h2>
<dl>
  <dt><%= I18n.t :use_customer_savings_for_purchase, scope: "activerecord.attributes.invoice" %></dt>
  <dd><%= I18n.t @draft_invoice.use_customer_savings_for_purchase, scope: "bool" %> <% if @draft_invoice.customer %>(<%= number_to_currency @draft_invoice.customer.total_savings %> beschikbaar)<% end %></dd>
  <dt><%= I18n.t :rental_type, scope: "activerecord.attributes.invoice" %></dt>
  <dd><%= I18n.t @draft_invoice.rental_type, scope: "activerecord.values.invoice.rental_type" %></dd>
  <dt><%= I18n.t :reference, scope: "activerecord.attributes.invoice" %></dt>
  <dd><%= @draft_invoice.reference || 'geen' %></dd>
  <% if @draft_invoice.recurrence_interval_in_months %>
    <dt><%= I18n.t :recurrence_interval_in_months, scope: "activerecord.attributes.invoice" %></dt>
    <dd><%= I18n.t :x_months, count: @draft_invoice.recurrence_interval_in_months, scope: "datetime.distance_in_words" %></dd>
  <% end %>
  <% if @draft_invoice.invoiceable_item_collection %>
    <dt><%= I18n.t :invoiceable_item_collection, scope: "activerecord.attributes.invoice" %></dt>
    <dd>
      <%= link_to "Werkgroepering", collection_management_work_set_url(@draft_invoice.invoiceable_item_collection) %>
      <%= button_to "Ververs", draft_invoice_refresh_path(@draft_invoice), method: :patch, data: {confirm: "Alle werken worden van de factuur verwijderd en de prijzen en kortingen worden opnieuw ingesteld conform de selectie in de werkgroepering. Weet je zeker dat je verder wilt gaan?"} %>
    </dd>
  <% end %>
</dl>
<h3>Opmerkingen</h3>
<p><small>Deze opmerkingen komen op de factuur te staan (<%= link_to "Bewerk", edit_draft_invoice_path(@draft_invoice)%>)</small></p>
<% end %>
<%= simple_format @draft_invoice.footertext %>

</div>
<div class="preview">
  <h2>Concept-factuur</h2>
  <% if @invoice_error %>
  <p class="alert hide-for-print"><%= @invoice_error %></p>

  <% end %>
  <% if @twinfield_invoice %>
    <%= render @twinfield_invoice %>
    <br/>
    <% if @draft_invoice.offer_invoice_specification? %>
    <%= render partial: 'twinfield/sales_invoices/specification', locals: {sales_invoice: @twinfield_invoice, uitleen_invoice: @twinfield_invoice.uitleen_invoice} %>
    <% end %>
  <% else %>
    <p>Voorlopige berekeningen</p>
    <%= render @draft_invoice  %>
  <% end%>
</div>