config/routes.rb
require "sidekiq/web"
require "letter_opener_web"

Rails.application.routes.draw do
  get "reports", to: "reports#index"
  get "reports/savings"
  get "reports/savings_per_year"
  get "reports/lent"
  get "reports/unfinished_ended"
  resources :articles
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new
  mount(LetterOpenerWeb::Engine, at: "/letter_opener", constraints: AdminConstraint.new) if Rails.env.staging? || Rails.env.development?
  namespace :api do
    namespace :v1 do
      resources :customers, only: [:index, :show]
      resources :works, only: [:show]
      resources :collections, only: [:index, :show] do
        resources :works, only: [:index, :show] do
        end
      end
    end
  end

  resources :reservations, except: [:new]

  resources :draft_invoices do
    collection do
      post :reset # , to: 'draft_invoices#reset'
    end
    resources :invoice_items do # , only: [:new, ,:destroy, :create] do
      get :edit_discount
    end
    get :mutation_form
    post :create_invoice
    patch :finalize_invoice
    patch :reviewed
    patch :refresh
  end

  resources :invoices do
    get "old_data", to: "invoices#old_data"
    get :specification, to: "invoices#specification"
    member do
      post :register_payment
      patch :on_hold
    end
  end

  resources :customers do
    get "raw", to: "customers#raw"
    resources :time_spans
    resource :collect_mandate
    resources :invoices
  end

  resources :collections do
    resources :works do
      resources :reservations
      resource :return, only: [:new, :create]
    end
  end

  resources :works, only: :show

  post "/auth/:provider/callback", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/new", to: "sessions#new"
  get "/application_status", to: "application#status"
  delete "/auth", to: "sessions#destroy", as: :auth

  root "application#home"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  LIMIT = 50

  before_action :authorize_show_report, except: [:index]

  def savings
    @customers_with_savings = Customer.with_savings.offset(params[:offset].to_i).limit(LIMIT)
  end

  def savings_per_year
    @data_per_year = {}
    customers = Customer.with_savings.select(:name, :external_customer_id, :customer_type, :uuid, :id).to_a.group_by(&:external_customer_id)

    @years = 2021..Time.now.year
    @year_data = {}
    @years.each do |year|
      data = ActiveRecord::Base.connection.execute(CostCenter.select("sum(cost_centers.value) AS value, customer_transactions.customer_code").customer_savings.final.join_customer_transactions.group("customer_transactions.customer_code").year(year).to_sql)
      customers.each do |customer_id, customer_set|
        customer = customer_set.first
        @year_data[year] = {data:}
        @data_per_year[customer_id] ||= {name: customer.name, type: customer.customer_type, customer_code: customer.external_customer_id, customer: customer}
        @data_per_year[customer_id][year] = -1 * data.find { |ii| ii["customer_code"] == customer_id }&.fetch("value", 0).to_f
        @data_per_year[customer_id]["#{year}_sum"] = @data_per_year[customer_id][year] + @data_per_year[customer_id]["#{year - 1}_sum"].to_f
      end
    end
    # data = ActiveRecord::Base.connection.execute(CostCenter.select("sum(cost_centers.value) AS value, customer_transactions.customer_code").customer_savings.final.join_customer_transactions.group("customer_transactions.customer_code").year(2021).to_sql)

    @years.each do |year|
      @year_data[year][:delta] = @year_data[year][:data].sum { |ii| -1 * ii["value"].to_f }
      @year_data[year][:sum] = @year_data[year][:delta] + @year_data[year - 1]&.[](:sum).to_f
    end

    # @header = @data_per_year.first.keys
  end

  def lent
    @time_spans = CollectionManagement::TimeSpan.where(current_user: current_user, classification: :rental_outgoing, status: :active, limit: 99999).select { |ts| ts.subject.is_a?(CollectionManagement::Work) }
    time_span_work_ids = @time_spans.map { |ts| ts.subject.id }.compact
    contact_uuids = @time_spans.map { |ts| ts.contact&.uuid }.compact

    @customer_hash = Customer.where(uuid: contact_uuids).map { |ii| [ii.uuid, ii] }.to_h

    credit_invoice_or_credited_invoice_ids = Invoice.where.not(credits_invoice_id: nil).pluck(:id, :credits_invoice_id).flatten
    invoice_items = InvoiceItem.includes(:invoice).works.where(invoiceable_id: time_span_work_ids).where.not(invoices: {id: credit_invoice_or_credited_invoice_ids})
    @invoice_hash = invoice_items.invoicing_period_spans_current.map { |ii| [ii.invoiceable_id, ii.invoice] }.to_h
    @invoice_last_month_hash = invoice_items.invoicing_period_spans_one_month_ago.map { |ii| [ii.invoiceable_id, ii.invoice] }.to_h
  end

  def unfinished_ended
    @time_spans = CollectionManagement::TimeSpan.where(current_user: current_user, classification: :rental_outgoing, status: :active, ends_at_lt: DateTime.current, limit: 99999).select { |ts| ts.subject.is_a?(CollectionManagement::Work) }

    time_span_work_ids = @time_spans.map { |ts| ts.subject.id }.compact
    contact_uuids = @time_spans.map { |ts| ts.contact&.uuid }.compact

    @customer_hash = Customer.where(uuid: contact_uuids).map { |ii| [ii.uuid, ii] }.to_h
    @invoice_hash = InvoiceItem.includes(:invoice).invoicing_period_spans_current.works.where(invoiceable_id: time_span_work_ids).map { |ii| [ii.invoiceable_id, ii.invoice] }.to_h
    @invoice_last_month_hash = InvoiceItem.includes(:invoice).invoicing_period_spans_one_month_ago.works.where(invoiceable_id: time_span_work_ids).map { |ii| [ii.invoiceable_id, ii.invoice] }.to_h
  end

  def index
    authorize! :index, ReportsController
  end

  private

  def authorize_show_report
    authorize! :show, ReportsController
  end
end

app/views/reports/index.html.erb
<h1>Rapportages</h1>
<h2>Speciale verzoeken</h2>
<ul>
  <li><%= link_to "Spaartegoeden en de uitgeleende werken", reports_savings_path%></li>
  <li><%= link_to "Totaaloverzicht uitgeleende werken", reports_lent_path%></li>
  <li><%= link_to "Verlopen uitleenacties", reports_unfinished_ended_path%></li>
</ul>

app/views/reports/lent.html.erb
<h1>Uitgeleende werken</h1>

<p>In deze rapportage worden alle uitgeleende werken getoond, met de klant en de factuur waarop de uitlening is verwerkt.</p>

<table class="sortable">
  <thead>
    <tr>
      <th>Inv. nummer</th><th>Vervaardiger</th><th>Titel</th><th>Klant ID</th><th>Klant</th><th>Uitgeleend sinds</th><th>Factuur</th>
    </tr>
  </thead>
  <tbody>
    <% @time_spans.each do |time_span| %>
      <% work = time_span.subject %>
      <% invoice = @invoice_hash[work.id.to_s]%>
      <% last_month_invoice = @invoice_last_month_hash[work.id.to_s]%>
      <% customer = time_span.contact ? @customer_hash[time_span.contact.uuid] : nil%>
      <tr>
        <td><%= link_to work.stock_number, collection_management_work_path(work)%></td>
        <td><%= work.artist_name_rendered%></td>
        <td><%= work.title_rendered%></td>
        <td><%= customer ? link_to(customer.id, customer) : "" %></td>
        <td><%= customer ? link_to(customer.name, customer) : "Geen klant" %></td>
        <td><%= I18n.l(time_span.starts_at.to_date, format: :short) if time_span.starts_at %></td>
        <td><%= if invoice
          link_to(invoice.invoice_number, invoice)
        elsif last_month_invoice
          link_to(last_month_invoice.invoice_number, last_month_invoice, class: :expired, title: "Factuur van vorige periode")
        end
        %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/savings.html.erb
<h1>Spaartegoeden</h1>
<table class="sortable">
<thead>
  <tr><th>Klant</th><th class="number">Spaartegoed</th><th class="number">Geleende werken</th></tr>
</thead>
<tbody>
<% @customers_with_savings.each do |customer|%>
  <tr><td><%= link_to customer%></td><td class="number" data-sortkey="<%= customer.total_savings.to_f%>"><%= number_to_currency customer.total_savings%></td><td class="number"><%= number_to_currency CollectionManagement::TimeSpan.where(current_user: current_user, contact_url: customer.uri, status: [:active], classification: :rental_outgoing, limit: 100, subject_type: "Work").map(&:subject).map{|a| a.selling_price.to_f}.sum %></td></tr>
<% end%>
</tbody>
</table>
<% if params[:offset].to_i >= ReportsController::LIMIT %>
<%= link_to "← Terug", reports_savings_path(offset: params[:offset].to_i - ReportsController::LIMIT)%>
<% end %>
<% if @customers_with_savings.count == ReportsController::LIMIT %>

<%= link_to "Vooruit →", reports_savings_path(offset: params[:offset].to_i + ReportsController::LIMIT)%>
<% end %>

app/views/reports/savings_per_year.csv.erb
<%=
data = [(["code","type","name"]+@years.map{|year| "#{year} delta"})+@years.map{|year| "#{year} total"}]
@data_per_year.each do |_, row|
  data << [row[:customer_code], row[:type], row[:name]] + @years.map { |year| row.send(:"[]",year).to_f.round(2) } + @years.map { |year| row.send(:"[]","#{year}_sum").to_f.round(2) }
end
data.map(&:to_csv).join("").html_safe

%>

app/views/reports/savings_per_year.html.erb
<h1>Spaartegoeden</h1>
<p>Toelichting: Op 1 juli 2022 heeft de overstap plaatsgevonden; in Twinfield zijn alle facturen geboekt vanaf 1 januari 2022. Vanuit de spaartegoeden van 30-6-2022 is teruggerekened naar de spaartegoeden op 31-12-2021. Getoond worden steeds eindejaarstotalen. Het huidige jaar is het totaal tot moment van draaien van de rapportage.</p>
<%= link_to 'Download als CSV', {action: 'savings_per_year', format: 'csv'}, class: 'button' %>
<table>
  <thead><tr><th>Jaar</th><th>Totaal spaartegoed</th><th>Mutatie</th></tr></thead>
  <tbody>
<% @years.each do |year| %>
    <tr>  <td><%= year %></td><td><%= number_to_currency @year_data[year][:sum] %></td><td><%= number_to_currency @year_data[year][:delta] %></td></tr>
<% end %>
</tbody>
</table>
<table class="sortable">
<thead>
  <tr>
    <th rowspan="2">Klantcode</th><th rowspan="2">Type</th><th rowspan="2">Naam</th><th colspan="<%=@years.count*2%>">Spaartegoed</th>
  </tr>
  <tr>
    <% @years.each do |year| %>
      <th class="number"><%=year%></th>
      <th class="number"><%=year%> tot.</th>
    <% end %>
  </tr>
</thead>
<tbody>
<% @data_per_year.each do |key, value|%>
  <tr>
    <td><%= link_to value[:customer_code], value[:customer]%></td><td><%= link_to value[:type], value[:customer]%></td><td><%= link_to value[:name], value[:customer]%></td>
    <% @years.each do |year| %>
      <td class="number" data-sortkey="<%= value[year].to_f%>"><%= number_to_currency value[year].to_f%></td>
      <td class="number" data-sortkey="<%= value["#{year}_sum"].to_f%>"><%= number_to_currency value["#{year}_sum"].to_f%></td>
    <% end %>
    </tr>
<% end%>
</tbody>
</table>

app/views/reports/unfinished_ended.html.erb
<h1>Actieve uitleenacties met een einddatum in het verleden.</h1>

<p>In deze rapportage worden alle werken getoond die nog een actieve uitleenactie hebben, maar waarvan de einddatum van die uitleen actie in het verleden ligt. Mogelijk zijn deze werken reeds terug maar onverwerkt, mogelijk is de huurperiode verlengt.</p>

<table class="sortable">
  <thead>
    <tr>
      <th>Inv. nummer</th><th>Vervaardiger</th><th>Titel</th><th>Klant</th><th>Uitgeleend sinds</th><th>Uitgeleend tot</th>
    </tr>
  </thead>
  <tbody>
    <% @time_spans.each do |time_span| %>
      <% work = time_span.subject %>
      <% invoice = @invoice_hash[work.id.to_s]%>
      <% last_month_invoice = @invoice_last_month_hash[work.id.to_s]%>
      <% customer = time_span.contact ? @customer_hash[time_span.contact.uuid] : nil%>
      <tr>
        <td><%= link_to work.stock_number, collection_management_work_path(work)%></td>
        <td><%= work.artist_name_rendered%></td>
        <td><%= work.title_rendered%></td>
        <td><%= customer ? link_to(customer.name, customer) : "Geen klant" %></td>
        <td><%= I18n.l(time_span.starts_at.to_date, format: :short) if time_span.starts_at %></td>
        <td><%= I18n.l(time_span.ends_at.to_date, format: :short) if time_span.ends_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>